# Site settings
title: Vivian Balakrishnan
email: Vivian@Balakrishnan.sg
description: People, Values, Thoughts, Activities
baseurl: ""
url: "http://VivianBalakrishnan.github.io"

# Build settings
markdown: kramdown
permalink: pretty
pygments: true
